(load "Token.scm")
(load "Token/Arr.scm")
(load "Token/Plus.scm")
(load "Token/Minus.scm")
(load "Token/Star.scm")
(load "Token/LP.scm")
(load "Token/RP.scm")
(load "Token/Ident.scm")
(load "Token/Int.scm")

(load "Lexer.scm")

(load "Expr.scm")
(load "Expr/Add.scm")
(load "Expr/Var.scm")
(load "Expr/Int.scm")
